### ISSUE TITLE
【（并不正经的）提问】这玩意是个啥

### ISSUE THREAD

**Issue by daizihan233** [Apa7-zero/gridea-theme-lin#11]
![image](https://user-images.githubusercontent.com/72146468/156483311-67e702ef-cebe-4747-b429-0bc802386c29.png)
~~这个地方是啥，别人老说我色色~~

**Comment by Apa7-zero** [comment]
> ![image](https://user-images.githubusercontent.com/72146468/156483311-67e702ef-cebe-4747-b429-0bc802386c29.png) ~这个地方是啥，别人老说我色色~

很显然，这是胖次
